package com.example.favouriterecipes.database

fun getRecipes() = listOf<Recipe>(
    Recipe(recipeName = "Vörösboros marhapörkölt", recipeDescription = "A húst megtisztítjuk, szárazra töröljük, és közepes kockákra vágjuk. A hagymát megpucoljuk, felaprítjuk, és 5 evőkanál olajon aranysárgára pirítjuk. Ekkor felöntjük kevés vízzel, és újból zsírjára sütjük. Közben megsózzuk.\n" +
            "A húst beledobjuk, és erős tűzön fehéredésig sütjük. Mikor kicsit levet engedett, mehet bele a pirospaprika, a kömény és két gerezd zúzott fokhagyma. A zöldpaprikát kimagozzuk, apró kockákra vágjuk, és beletesszük. Kevés vizet öntünk bele, és megsózzuk. Hagyjuk főni, közben megsózzuk, megborsozzuk. Félidőben megfűszerezzük a kakukkfűvel és majorannával, de épp csak egy csipetnyit adunk hozzá.\n" +
            "Mikor kb. 1 óra múlva a hús félpuha, hozzáadjuk a felkockázott, meghámozott paradicsomot és a vörösbort is, és barnásra főzzük. A legvégén még egyszer beízesítjük zúzott fokhagymával és köménnyel. Amikor a pörköltünk zamatos, fűszeres, barnás és sűrű, elészült. Főtt krumplival vagy nokedlivel kínáljuk."),
    Recipe(recipeName = "Gulyásleves", recipeDescription = "A felhevített zsíron üvegesre pároljuk az apróra vágott vöröshagymát. Ezután hozzáadjuk a felkockázott, sózott, borsozott húst, majd fehéredésig pirítjuk. Amikor kifehéredett, megszórjuk a pirospaprikával és az ételízesítővel, felöntjük 0,5 dl vízzel, majd pár percig kevergetve pároljuk. Ezután felöntjük annyi vízzel, hogy jól ellepje, majd félpuhára főzzük a húst.\n" +
            "Amikor a hús félig megpuhult, hozzáadjuk az ízlés szerint felvágott sárgarépát, petrezselymet, zellert, paprikát és a paradicsomot, majd még egy kevés vízzel felöntjük. Hozzáadjuk az egész borsokat, a köménymagot és a sót, és így főzzük tovább.\n" +
            "Amikor a hús már majdnem teljesen megpuhult (kb. 35 perc múlva), beletesszük kockára vágott krumplit, és 10 perc alatt teljesen készre főzzük a levest. Tálaláskor a leves mellé kínálhatunk kenyérszeleteket, vagy pogácsát."),
    Recipe(recipeName = "Túrós csusza", recipeDescription = "A tésztát a csomagoláson található előírás szerint forró, sós vízben kifőzzük, majd lecsepegtetjük.\n" +
            "A szalonnát kockára vágva pörcösre sütjük. Amikor kisült, a zsírját a tésztára öntjük, hozzákeverjük a fele túrót, a tejföl felét és a pörcök felét is, megsózzuk.\n" +
            "Tűzálló tálban sütőbe tesszük, tetejére tejfölt simítunk és az egészet összesütjük. Tálaláskor teszünk még rá túrót, tejfölt és pörcöt."),
    Recipe(recipeName = "Gundel palacsinta", recipeDescription = "Csomómentesre keverjük a tészta hozzávalóit, 30 percig pihentetjük, majd étolajjal vékonyan kikent palacsintasütőben 14 db palacsintát sütünk a szokásos módon.\n" +
            "A töltelékhez felforraljuk a tejet a cukorral és a citromhéjjal, majd levesszük a tűzről. Belekeverjük a diót, a mazsolát és a rumot. Az öntethez simára keverjük a tojássárgáját és a lisztet 1 dl tejjel. Felforrósítjuk a maradék tejet, a kakaóport és a darabokra tört csokoládét. Vékony sugárban hozzáöntjük a tojást, és lassú tűzön, folyamatosan kevergetve besűrítjük (nem forraljuk fel, nehogy kicsapódjon a tojás!). Végül rummal ízesítjük.\n" +
            "Megtöltjük a palacsintákat a diós töltelékkel, azután feltekerjük vagy félbe, majd negyedbe hajtjuk, és tálra helyezzük őket, úgy, hogy félig fedjék egymást. Forró csokoládéöntettel és tejszínhabbal tálaljuk."),
    Recipe(recipeName = "Pásztortarhonya", recipeDescription = "A hagymát, a krumplit megpucoljuk, apróra vágjuk. A kolbászt tetszőleges vastagságúsra felszeleteljük.\n" +
            "A tarhonyát az előre felforrósított olajban megpirítjuk, majd az apróra vágott hagymát ezen az alapon megdinszteljük. Levesszük a tűzről. Fűszerezzük sóval, borssal, pirospaprikával, ízlés szerint. Ezután mehet bele a krumpli és kolbász bele, majd annyi vízzel felöntöjük, hogy ellepje az egészet, de ez a mennyiség legyen kétszer annyi, mint amennyi tarhonyát használtunk. Időközönként keverjük meg.\n" +
            "Amikor a víz kezd elleforrni róla, fedjük le, és alacsony hőmérsékleten pároljuk addig, amíg a tarhonya meg nempuhul. Nem kell, hogy teljesen száraz legyen, a krumpli és a tarhonya úgyis felszívja azt a kicsit, ami marad."),
    Recipe(recipeName = "Lecsó", recipeDescription = "A paradicsomot leforrázzuk, meghámozzuk, gerezdekre vágjuk. A zöldpaprikát megmossuk, kicsumázzuk, ereit és magjait eltávolítjuk, majd  ujjnyi vastag karikákra szeljük. A hagymát meghámozzuk, és apróra felkockázzuk. A szalonnát ugyancsak apró kockákra vágjuk.\n" +
            "Az olajhoz adjuk a szalonnát, és mérsékelt tűzön zsírjából kisütjük. Megfonnyasztjuk benne a hagymát, majd lehúzzuk a tűzről, megszórjuk a pirospaprikával, rádobjuk a paradicsomot, ízlés szerint sózzuk. Visszatesszük a tűzre, és néhány percig fedő nélkül forraljuk.\n" +
            "Beleforgatjuk a zöldpaprikát, és félig lefedve, mérsékelt tűzön puhára főzzük 10 perc alatt, végül megsózzuk.\n" +
            "Petrezselymes burgonyával, párolt rizzsel vagy friss házikenyérrel kínáljuk."),
    Recipe(recipeName = "Paprikás krumpli", recipeDescription = "A hagymát megtisztítjuk és kockára vágjuk. Kevés olajat forrósítunk egy lábasban, beletesszük a hagymát, üvegesre pirítjuk, hozzáadjuk a felkarikázott kolbászt, majd megpirítjuk. \n" +
            "Lehúzzuk a lábast a tűzhelyről, megszórjuk a pirospaprikával. Átkeverjük, majd hozzáadjuk a megmosott, megtisztított és kockára vágott burgonyát, és felöntjük annyi vízzel, ami majdnem ellepi. Megsózzuk, paradicsompürét teszünk bele, és addig főzzük, amíg a burgonya megpuhul.\n" +
            "Friss kenyérrel, savanyú uborkával tálaljuk."),

    Recipe(recipeName = "Töltött káposzta", recipeDescription = "A vöröshagymát zsírban megpirítjuk, a felét kivesszük a töltelékhez. A darált húst összekeverjük a tojással, a félig megfőtt rizzsel, a pirított vöröshagymával, a reszelt fokhagymával, sóval, borssal, majd belegöngyöljük a káposztalevelekbe. (Ha nem kapunk savanyított leveleket, az édes káposzta torzsáját vágjuk ki, tegyük fel főni ecetes, sós vízben, főzés közben sorban leválnak a levelei.)\n" +
            "A maradék pirított hagymát megszórjukpirospaprikával, teszünkrá egy kevés savanyú káposztát, rátessszüka füstölt oldalast (kicsitbeáztatjuk, hogy ne legyen túl sós), majd ismét káposzta jön, azután sorban a töltött gombócokat, a tetejére káposzta kerül. Felöntjükvízzel, sózzukborsozzuk, köményt szórunkrá és beletessszüka babérlevelet is. 160 fokos sütőben, lefedve 2 órát pároljuk.\n" +
            "Pirított szalonnával, tejföllel tálaljuk."),
    Recipe(recipeName = "Kocsonya", recipeDescription = "A füstölt tarját, a megtisztított körmöket és a sertésbőrt egy nagy fazékba tesszük és annyi vízzel öntjük fel, hogy bőven ellepje. Miután felforrt, lehabozzuk, beletesszük a gerezdekre szedett fokhagymát, a fekete borsot, a vöröshagymát és ízlés szerint sózzuk. A kocsonyát addig főzzük, ameddig a körömnél a húsos-bőrös rész szinte már leválik a csontról (kb. 2-3 óra). A tarját 1 óra után kivesszük.\n" +
            "Amikor a kocsonya készre főtt, pihentetjük 10 percet az asztalon, először kanállal leszedjük a a zsírt, majd papírtörlőt tépünk és rátesszük a kocsonya lé tetejére. Pár másodpercig hagyjuk rajta, ennyi idő elég arra, hogy a papírtörlő magába szívja a zsír réteget. A papírtörlőt ezután óvatosan levesszük a kocsonya tetejéről. Szükség szerint ez a lépés megismételhető.\n" +
            "Tálba tesszük a kicsontozott körmöket, bőröket és a tarját, majd felöntjük a szűrt kocsonyalével. A kiadagolt kocsonyát hideg helyen hagyjuk kihűlni, megdermedni."),
    Recipe(recipeName = "Sezegedi halászlé", recipeDescription = "A megtisztított halakat kifilézzük. A halfiléket feldaraboljuk, megsózzuk és felhasználásig hűtőbe rakjuk.\n" +
            "A csontokat és a halfejet egy edénybe tesszük, rádaraboljuk a hagymát, a fokhagymát, sózzuk, majd felöntjük 2 liter hideg vízzel és kb. 1,5 órán keresztül főzzük.\n" +
            "Ha az alaplé elkészült, akkor egy tésztaszűrőn átpasszírozzuk. Az átpasszírozott alaplevet újra tűzre tesszük, hozzáadjuk pirospaprikát, 2 perc forralás után a halfiléket is, (amennyiben halbelsőségünk is van, azt is ezzel együtt főzzük meg) és 10 perc alatt puhára főzzük. Felkarikázott erőspaprikával ízesíthetjük a levest. "),
    Recipe(recipeName = "Krumplileves", recipeDescription = "A krumplit tisztítás után kis kockákra, a hagymákat finomra vágjuk. A burgonyát 1 liter vízben a babérlevéllel, a majorannával és 1 csipet sóval megfőzzük. \n" +
            "Felhevített zsiradékban a lisztet zsemleszínűre pirítjuk, ebben megdinszteljük a vöröshagymát, majd a fokhagymát. Félrehúzzuk a tűzhelyről, elkeverjük a paprikával, felöntjük 2 dl vízzel, majd a burgonyához öntjük. Fűszerezzük, és lassú forralással 5 percig főzzük.\n" +
            "A tejfölt kevés forró levessel kikeverjük, kevergetve hozzácsorgatjuk a leveshez. Rövid ideig együtt forraljuk, a végén az ecettel enyhén pikánsra savanyítjuk, és rövid pihentetés után tálaljuk. A felaprított zelletzölddel tálaljuk. "),
    Recipe(recipeName = "Aranygaluska", recipeDescription = "A tejet felmelegítjük, majd belemorzsoljunk a frissélesztőt, elkeverjük és hagyjuk felfutni.Egytálba szitáljuk a lisztet, hozzáadjunk a cukrot, az élesztős keveréket, továbbá 3 db tojássárgáját, és fakanállal addig keverjük, amíg a massza el nem válik az edény falától.Letakarjukegy darab folpakkal, és meleg helyen a tésztát a duplájára kelesztjük.\n" +
            "Lisztezett deszkán nyújtani kezdjük a tésztát. Akkor jó, ha 2 cm vastag, majd pogácsaszaggatóval köröket szúrunk ki belőle, és azokat gombóccá formázzuk. Megolvasztjuk a vajat, belemártjuk a tésztagombócokat, majd meghempergetjük őketadarált mákban. 4-6 db tűzálló tálkába rendezzük, további 15 percig ebben kelnek a tészták, végül 200 fokon 10-15 perc alatt aranyszínűre sütjük.\n" +
            "A borsodóhoz egy kerek aljú fémtálba öntjük a 3 db tojássárgáját, a 2 db tojást, a kristálycukrot, valamintapezsgőt, és vízgőz fölött, állandó kevergetés mellett sűrűre fűzzük. Az aranygaluskátmeghintjükegy kevés porcukorral, és a borsodóval meglocsolva tálaljuk."),
    Recipe(recipeName = "Zöldborsós brassói", recipeDescription = "A zöldborsót, ha mirelit, kivesszük a fagyasztóból, és szobahőmérsékleten hagyjuk felengedni, ha friss zöldborsót használunk, megmossuk és lecsepegtetjük.\n" +
            "A szűzpecsenyét kisebb kockákra vágjuk, enyhén megsózzuk és -borsozzuk, majd összekeverjük, és kb. 15 percig hagyjuk állni, hogy az ízek átjárják.\n" +
            "Egy serpenyőben kevés olajon fehéredésig pirítjuk a fűszeres húst, majd hozzáadjuk az apróra vágott fokhagymát, és 5-6 percig pároljuk. Ezután hozzáadjuk a zöldborsót, ízlés szerint megsózzuk, -borsozzuk, és pár perc alatt zsírjára sütjük. Tálalásig melegen tartjuk.\n" +
            "A krumplit megpucoljuk, kisebb kockákra vágjuk. Enyhén sós vízben pár perc alatt félpuhára főzzük, leszűrjük, és hagyjuk kicsit hűlni. Az olajat ízlés szerint összekeverjük a sóval, majd a félpuhára főzött krumplira öntjük, és óvatosan összeforgatjuk.\n" +
            "Egy sütőpapírral bélelt tepsire terítjük az olajjal összekevert krumplit, majd előmelegített sütőbe toljuk, és közepes hőmérsékleten szép pirosra sütjük. Tálaláskor a sült krumplira kanalazzuk a zöldborsós brassóit, és megszórjuk az apróra vágott petrezselyemmel."),
    Recipe(recipeName = "Zöldséges bableves", recipeDescription = "Előző este a babot szűrőbe téve leöblítjük, aztán beáztatjuk bő hideg vízbe. Másnap leszűrjük, aztán ismét leöblítjük.\n" +
            "A vörös- és a fokhagymát meghámozzuk, finomra vágjuk. A burgonyát, a kétféle répát és a szárzellert megtisztítjuk, felkockázzuk. A karfiolt megmossuk, apró rózsákra bontjuk.\n" +
            "Egy lábasban felforrósítjuk az olajat, és megfonnyasztjuk benne a hagymákat. Hozzákeverjük a paradicsompürét, aztán 1 percig pirítjuk. Ha ezzel elkészültünk, hozzáadjuk a babot, felöntjük vízzel, majd felforraljuk. Ezután sózzuk, és félpuhára főzzük.\n" +
            "A babos alaphoz adjuk az előkészített zöldségeket, sózzuk, borsozzuk, majd kis lángon az egészet puhára főzzük. Ha szükséges, ismét megsózzuk, majd finomra vágott petrezselyemmel tálaljuk.")
)